version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: inception_nginx
    ports:
      - 443:443
    volumes:
      - html:/var/www/html
    networks:
      - net
    depends_on:
      - wp
    restart: unless-stopped
  wp:
    build: ./wordpress
    container_name: inception_wp
    volumes:
      - html:/var/www/html
    networks:
      - net
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped
  db:
    build: ./mariadb
    container_name: inception_db
    volumes:
      - database:/var/lib/mysql
    networks:
      - net
    env_file:
      - .env
    restart: unless-stopped

volumes:
  html:
    driver: local
    driver_opts:
      type: none
      device: /home/kali/data/html
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/kali/data/database
      o: bind

networks:
  net:
    driver: bridge

