#!/bin/sh

echo "GRANT ALL ON *.* TO '$MYSQL_ROOT_USER'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS $MYSQL_DB;
CREATE USER '$MYSQL_USER'@'inception_wp.inception_net' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON *.* TO '$MYSQL_USER'@'inception_wp.inception_net';
FLUSH PRIVILEGES;"
